Add dependency downloading to install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,6 +2,21 @@
 
 set -e
 
+brewNerdFonts='font-hack-nerd-font'
+paruNerdFonts='ttf-hack-nerd'
+packagesNeeded='neovim ripgrep starship stylua shfmt shellcheck prettier deno antigen'
+if [ -x "$(command -v brew)" ] 
+then 
+  brew install $packagesNeeded $brewNerdFonts
+elif [ -x "$(command -v paru)" ]
+then 
+  paru
+  paru -S $packagesNeeded $paruNerdFonts
+else 
+  echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2
+  exit
+fi
+
 CONFIG="install.conf.yaml"
 DOTBOT_DIR="dotbot"
 
